### PR TITLE
Fixed #4.  Create chapter_02

### PR DESCRIPTION
**Pull request by cliu23**
Finished chapter 2 with the help with my friends!

### CODE REVIEW

**Comment by ladanazita** [comment]
Great job!!!!!

**Comment by cliu23** [comment]
nice!

**Comment by ladanazita** [comment]
I actually can't merge this!! There are conflicts. Let me look at it and see what we need to do!

**Comment by ladanazita** [comment]
It looks like you didn't do a pull before editing the story.txt! Sean had contributed to that file so you didn't edit on an updated version of it!

**Comment by cliu23** [comment]
alright i recommitted chapter 2

**Comment by ladanazita** [comment]
Hey calvin, sean just finished adding chapter five, can you do a git pull on master and redo chapter two ? lol sorry about that!

**Comment by SeanMoo** [comment]
I noticed we are still missing a Chapter 02

**Comment by ladanazita** [comment]
@SeanMoo good looking out
 @cliu23 should be on it!

**Pull request closed without merging**
